INSERT INTO staff VALUES 
(null,'Abdou','English Teacher',2,null,null,null,'abdou.png',null,null),
(null,'David','Math Teacher',2,null,null,null,'david.png',null,null),
(null,'Mukabahinda Betty','Social studies Teacher',2,null,null,null,'betty.png',null,null),
(null,'Hakizimana Prosper','French Teacher',2,null,null,null,'prosper.png',null,null),
(null,'Dieudonne','Kinyarwanda Teacher',2,null,null,null,'dieudonne.png',null,null),
(null,'Sibomana Emmanuel','Kinyarwanda Teacher',2,null,null,null,'emmanuel.png',null,null),
(null,'Niyonsaba Evariste','French Teacher',2,null,null,null,'evariste.png',null,null),
(null,'Omutta Joshua','English Teacher',2,null,null,null,'joshua.png',null,null),
(null,'Joel','English Teacher',2,null,null,null,'joel.png',null,null),
(null,'Ngavubwiko Claude','Kinyarwanda Teacher',2,null,null,null,'claude.png',null,null),
(null,'School Principal','Principal',1,null,null,null,'placeholder.jpg',null,null),
(null,'Carlos','Head Teacher',1,null,null,null,'carlos.png',null,null),
(null,'Accountant','Accountant',1,null,null,null,'placeholder.jpg',null,null),
(null,'Jeannette','Secretary',1,null,null,null,'jeanette.png',null,null);